### ISSUE TITLE
Major known issue: Apparently the unofficial ProtonMail desktop client's locale manifest's resulting filepath when extracted is too long for Windows without using the long file paths Registry key.

### ISSUE THREAD

**Issue by DrewNaylor** [DrewNaylor/guinget#149]
Here's a screenshot:
![Can't find unofficial protonmail desktop locale](https://user-images.githubusercontent.com/15517419/159128399-c7fb340d-53d4-4157-80bd-ac8dee191c9d.png)

I figured out it's probably too long for Windows by trying to rename its installer file to the locale file, and I couldn't put the entire extension in, so it just ended up as a `.y` file. Perhaps there should be a way to handle these situations by deferring to winget for package information not available in the database file. Unfortunately, this is a problem in v0.3.0.1, and a fix won't be available immediately as I want to take a break for now.

(Edit: I'm pretty sure it is a max path limitation, as the path is 259 characters and the default limit without opting into extended paths is 260, and I'm sure .NET Framework adds a null-terminator to the end: https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation

What I can do is let the user choose whether to ignore manifests that are too long, get their info from winget, or use the long file paths by changing the registry.)

See also #148 as that one is somewhat related due to this one manifest causing the rest to not extract or load.

For now you can right-click a package and select `Show in winget...` to get package details for unloaded manifests.

**Comment by DrewNaylor** [comment]
I'll have to create a CLI app that can be run to set the long file path support in the Registry. There will be the three radio buttons, and selecting the one to use long file paths will pop up a message box asking if the user wants to turn on long file path support, so they don't have to use a button for it. Clicking "No" will go back to their saved setting, but clicking "yes" will open UAC for running the CLI app to set long file path support. If long file path support is currently on in the Registry when the Options window is open, a button to turn it off will be enabled for people to use if they want to. Clicking the button will also reset to always asking the user. A messagebox will also let the user know that's going to happen, with an option to continue or not.

**Comment by DrewNaylor** [comment]
Maybe UNC paths (`\\C:\` for example) would be another option, but that requires more work and testing from me.

**Comment by SvenErik1968** [comment]
I have the long paths settings enabled in the registry (on Win11, settings date back to from before I ugraded from Win10), but I still get this error:

![registry](https://user-images.githubusercontent.com/10983802/165711192-4c03a634-cfec-41e5-a68b-56ad96a419e6.png)

![guinget](https://user-images.githubusercontent.com/10983802/165711262-f585e988-9d4e-4647-ac70-21a93cb626c0.png)

Maybe another possible solution would be to allow a manually set temp folder? I still use a `C:\Temp` folder; if I could use that, it would reduce the length of the temp-path (`C:\Users\Sven-Erik\AppData\Local\winget-frontends\source\winget-pkgs\temp\`) from, in my case, 74 to 8 chars.

**Comment by DrewNaylor** [comment]
I still have to set `longPathAware` in the manifest even if it's set in the Registry, which is probably why you're still running into it. It's good to know there are other manifests with the issue. Allowing a custom manifest directory root is a good idea, I'll add that option in the next version. Thank you for suggesting it.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
```
---------------------------
Extracting manifests
---------------------------
 "C:\Users\Sven-Erik\AppData\Local\winget-frontends\source\winget-pkgs\temp\winget-pkgs-master\winget-pkgs-master\manifests\u\unofficial-protonmail-desktop\unofficial-protonmail-desktop\1.2.1\unofficial-protonmail-desktop.unofficial-protonmail-desktop.locale.en-US.yaml" 
---------------------------
OK   
---------------------------

```

**Comment by DrewNaylor** [comment]
Update: version 0.3.0.2 fixes this bug and should now be available in winget. This issue will be closed when the code is ported to v0.4.

**Comment by DrewNaylor** [comment]
I have just improved this so that it properly stops letting you know that it couldn't extract files with paths that are too long if long file path support is unavailable. This change will be added to v0.4, as I'm not planning on doing any more v0.3.x releases due to that version not having the nearly-instant search and usually-faster package list loading code. This shouldn't be an issue right now though, as the manifest for the unofficial ProtonMail client was either removed or renamed to be shorter and fit within 259 characters.

**Comment by DrewNaylor** [comment]
It's in v0.4 now.
